# Generated by Django 5.2 on 2025-06-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_applicant_resume'),
        ('jobs', '0004_auto_20200809_0813'),
    ]

    operations = [
    ]
