# Generated by Django 5.2 on 2025-05-25 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0005_tag_alter_category_options_joke_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
    ]
