# Generated by Django 5.2 on 2025-05-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0006_alter_category_options_alter_tag_options'),
        ('jokes', '0008_joke_user'),
    ]

    operations = [
    ]
