# Generated by Django 5.2 on 2025-05-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0009_merge_20250531_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='user',
        ),
    ]
