# Generated by Django 5.2 on 2025-06-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0009_auto_20200809_1146'),
        ('jokes', '0012_jokevote'),
    ]

    operations = [
    ]
